/** Biblioteca inicial de ejercicios de patinaje (GESTION_DEPORTIVA §5.1). Datos puros, sin base de datos. */

export const EXERCISE_COMPONENTS = [
  "WARMUP",
  "TECHNIQUE",
  "PHYSICAL",
  "SPEED",
  "ENDURANCE",
  "TACTICS",
  "GAME",
  "COOLDOWN",
] as const;
export type ExerciseComponent = (typeof EXERCISE_COMPONENTS)[number];

export type ExerciseTemplate = {
  name: string;
  component: ExerciseComponent;
  minutes: number;
  materials: string;
  space: string;
  description: string;
  /** Niveles sugeridos (por nombre); vacío = todos. */
  levels: string[];
  /** Solo para escuelas de patinaje (calentamientos y juegos en patines). */
  skatingOnly?: boolean;
};

/** Ejercicios para cualquier modalidad (calentamiento, físico, vuelta a la calma). */
export const COMMON_EXERCISES: ExerciseTemplate[] = [
  {
    name: "Movilidad articular",
    component: "WARMUP",
    minutes: 8,
    materials: "",
    space: "Zona seca",
    description: "Tobillos, rodillas, cadera, hombros y cuello, 10 repeticiones por articulación.",
    levels: [],
  },
  {
    name: "Trote suave con cambios de ritmo",
    component: "WARMUP",
    minutes: 8,
    materials: "",
    space: "Zona seca",
    description: "Trote continuo; al silbato, 10 s más rápido y volver al ritmo base.",
    levels: [],
  },
  {
    name: "Skipping y talones",
    component: "WARMUP",
    minutes: 6,
    materials: "Conos",
    space: "Zona seca",
    description: "Dos series de 15 m de skipping, talones a glúteo y desplazamiento lateral.",
    levels: [],
  },
  {
    name: "Patinaje suave de activación",
    component: "WARMUP",
    minutes: 10,
    materials: "",
    space: "Pista",
    description: "Vueltas a ritmo cómodo, posición relajada, respiración controlada.",
    levels: [],
    skatingOnly: true,
  },
  {
    name: "Juego de la lleva en patines",
    component: "GAME",
    minutes: 10,
    materials: "Petos",
    space: "Pista o parque",
    description: "Un perseguidor; quien es tocado cambia de rol. Delimitar el área con conos.",
    levels: ["Iniciación", "Formación"],
    skatingOnly: true,
  },
  {
    name: "Sentadillas isométricas en posición",
    component: "PHYSICAL",
    minutes: 8,
    materials: "Cronómetro",
    space: "Zona seca",
    description: "3 series de 30–45 s en posición de patinaje, descanso de 30 s.",
    levels: [],
  },
  {
    name: "Saltos laterales (skater jumps)",
    component: "PHYSICAL",
    minutes: 8,
    materials: "",
    space: "Zona seca",
    description: "Saltos de un pie al otro con estabilización de 1 s; 3 series de 12.",
    levels: [],
  },
  {
    name: "Plancha y core",
    component: "PHYSICAL",
    minutes: 8,
    materials: "Colchonetas",
    space: "Zona seca",
    description: "Plancha frontal, lateral y puente de glúteo; 3 rondas de 30 s.",
    levels: [],
  },
  {
    name: "Escalera de coordinación",
    component: "PHYSICAL",
    minutes: 10,
    materials: "Escalera de agilidad",
    space: "Zona seca",
    description: "Dentro-fuera, lateral y en zigzag; énfasis en apoyos rápidos.",
    levels: [],
  },
  {
    name: "Equilibrio en un pie",
    component: "PHYSICAL",
    minutes: 6,
    materials: "",
    space: "Zona seca",
    description: "30 s por pierna con ojos abiertos y luego cerrados; progresar a superficie inestable.",
    levels: [],
  },
  {
    name: "Fondo aeróbico en zona seca",
    component: "ENDURANCE",
    minutes: 20,
    materials: "",
    space: "Zona seca",
    description: "Trote continuo a intensidad moderada (puede hablar con frases cortas).",
    levels: ["Intermedio", "Avanzado", "Competencia"],
  },
  {
    name: "Vuelta a la calma patinando",
    component: "COOLDOWN",
    minutes: 5,
    materials: "",
    space: "Pista",
    description: "Vueltas muy suaves, posición alta, respiración profunda.",
    levels: [],
    skatingOnly: true,
  },
  {
    name: "Estiramientos de tren inferior",
    component: "COOLDOWN",
    minutes: 8,
    materials: "Colchonetas",
    space: "Zona seca",
    description: "Cuádriceps, isquiotibiales, aductores, glúteo y gemelos; 30 s cada uno.",
    levels: [],
  },
  {
    name: "Respiración y cierre del grupo",
    component: "COOLDOWN",
    minutes: 4,
    materials: "",
    space: "Cualquiera",
    description: "Respiraciones lentas y retroalimentación breve de lo trabajado en la clase.",
    levels: [],
  },
];

/** Ejercicios propios de patinaje de velocidad, por nivel. */
export const SPEED_EXERCISES: ExerciseTemplate[] = [
  {
    name: "Posición básica en parado",
    component: "TECHNIQUE",
    minutes: 8,
    materials: "",
    space: "Pista",
    description: "Rodillas flexionadas, peso al centro, manos adelante; mantener 20 s y relajar.",
    levels: ["Iniciación"],
  },
  {
    name: "Marcha de pato",
    component: "TECHNIQUE",
    minutes: 8,
    materials: "",
    space: "Pista",
    description: "Pasos cortos con puntas hacia afuera para ganar confianza y empuje.",
    levels: ["Iniciación"],
  },
  {
    name: "Caída segura y levantarse",
    component: "TECHNIQUE",
    minutes: 8,
    materials: "Protecciones",
    space: "Pista",
    description: "Caer hacia adelante sobre rodilleras y muñequeras; levantarse en tres apoyos.",
    levels: ["Iniciación"],
  },
  {
    name: "Frenado en T",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Conos",
    space: "Pista",
    description: "Arrastre del patín trasero perpendicular; frenar antes de la línea de conos.",
    levels: ["Iniciación", "Formación"],
  },
  {
    name: "Slalom de conos",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "10 conos",
    space: "Pista",
    description: "Conos a 1,5 m; pasar en zigzag con ambos pies sin levantar los patines.",
    levels: ["Iniciación", "Formación"],
  },
  {
    name: "Deslizamiento en un pie",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Conos",
    space: "Pista",
    description: "Impulso y deslizar el mayor tiempo posible en un patín; alternar piernas.",
    levels: ["Iniciación", "Formación"],
  },
  {
    name: "Empuje lateral completo",
    component: "TECHNIQUE",
    minutes: 12,
    materials: "",
    space: "Pista",
    description: "Extensión total de la pierna hacia el lado y recogida bajo la cadera.",
    levels: ["Formación", "Intermedio"],
  },
  {
    name: "Cruce en curva con conos",
    component: "TECHNIQUE",
    minutes: 15,
    materials: "8 conos",
    space: "Pista",
    description: "Curva marcada con conos; cruces continuos sin perder la posición baja.",
    levels: ["Formación", "Intermedio"],
  },
  {
    name: "Patinaje hacia atrás",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "",
    space: "Pista",
    description: "Medias lunas hacia atrás mirando por encima del hombro.",
    levels: ["Formación"],
  },
  {
    name: "Recta en posición aerodinámica",
    component: "TECHNIQUE",
    minutes: 12,
    materials: "",
    space: "Pista",
    description: "Rectas con espalda horizontal y manos atrás; corregir altura de cadera.",
    levels: ["Intermedio", "Avanzado"],
  },
  {
    name: "Salida desde parado",
    component: "SPEED",
    minutes: 12,
    materials: "Silbato",
    space: "Pista",
    description: "Posición de salida, primeros 4 pasos de carrera y transición al empuje.",
    levels: ["Intermedio", "Avanzado", "Competencia"],
  },
  {
    name: "Sprints de 50 m",
    component: "SPEED",
    minutes: 15,
    materials: "Cronómetro, conos",
    space: "Pista",
    description: "6–8 sprints al máximo con recuperación completa (2 min).",
    levels: ["Intermedio", "Avanzado", "Competencia"],
  },
  {
    name: "Doble empuje",
    component: "TECHNIQUE",
    minutes: 15,
    materials: "",
    space: "Pista",
    description: "Empuje hacia adentro y hacia afuera en cada zancada; progresar de lento a rápido.",
    levels: ["Avanzado", "Competencia"],
  },
  {
    name: "Curva a velocidad",
    component: "SPEED",
    minutes: 15,
    materials: "Conos",
    space: "Pista",
    description: "Entrada lanzada a la curva, cruces rápidos y salida explosiva.",
    levels: ["Intermedio", "Avanzado", "Competencia"],
  },
  {
    name: "Series de 400 m",
    component: "ENDURANCE",
    minutes: 20,
    materials: "Cronómetro",
    space: "Pista",
    description: "4–6 repeticiones a ritmo de 1.000 m con recuperación de 2 min.",
    levels: ["Avanzado", "Competencia"],
  },
  {
    name: "Fondo continuo en pista",
    component: "ENDURANCE",
    minutes: 25,
    materials: "",
    space: "Pista o ruta",
    description: "Patinaje continuo a intensidad moderada; controlar postura con la fatiga.",
    levels: ["Intermedio", "Avanzado", "Competencia"],
  },
  {
    name: "Relevos en grupo",
    component: "TACTICS",
    minutes: 15,
    materials: "",
    space: "Pista",
    description: "Tren de 4–6 patinadores; el primero sale por fuera y se ubica al final.",
    levels: ["Intermedio", "Avanzado"],
  },
  {
    name: "Ataque y respuesta",
    component: "TACTICS",
    minutes: 15,
    materials: "Silbato",
    space: "Pista",
    description: "En grupo, al silbato un patinador ataca y el resto debe cerrar el hueco.",
    levels: ["Avanzado", "Competencia"],
  },
  {
    name: "Lectura de carrera: posición en el pelotón",
    component: "TACTICS",
    minutes: 15,
    materials: "",
    space: "Pista",
    description: "Simulación de carrera por puntos; ubicarse y elegir cuándo adelantar.",
    levels: ["Avanzado", "Competencia"],
  },
  {
    name: "Simulación de 1.000 m",
    component: "SPEED",
    minutes: 15,
    materials: "Cronómetro",
    space: "Pista",
    description: "Prueba controlada a ritmo de competencia con parciales por vuelta.",
    levels: ["Competencia"],
  },
  {
    name: "Carrera de eliminación",
    component: "GAME",
    minutes: 12,
    materials: "Silbato",
    space: "Pista",
    description: "Cada vuelta sale el último; trabaja velocidad y ubicación.",
    levels: ["Formación", "Intermedio", "Avanzado"],
  },
  {
    name: "Relevos por equipos",
    component: "GAME",
    minutes: 12,
    materials: "Testigos, conos",
    space: "Pista",
    description: "Equipos de 3–4 con entrega de testigo; mezcla de niveles.",
    levels: [],
  },
  {
    name: "Saltos de obstáculos bajos",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Vallas bajas",
    space: "Pista",
    description: "Saltar vallas de 10–15 cm con ambos pies y aterrizar estable.",
    levels: ["Formación", "Intermedio"],
  },
  {
    name: "Cambios de dirección",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Conos",
    space: "Pista",
    description: "Recorrido en 8 y giros de 180°; mirar hacia donde se va.",
    levels: ["Iniciación", "Formación"],
  },
  {
    name: "Técnica de llegada (lanzamiento de patín)",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Línea de meta",
    space: "Pista",
    description: "Adelantar el patín en la línea de meta manteniendo el equilibrio.",
    levels: ["Avanzado", "Competencia"],
  },
  {
    name: "Fuerza en cuestas",
    component: "PHYSICAL",
    minutes: 15,
    materials: "",
    space: "Ruta con pendiente",
    description: "Subidas cortas de 20–30 s con empuje completo, bajar recuperando.",
    levels: ["Avanzado", "Competencia"],
  },
];

/** Ejercicios propios de natación (#71). */
export const SWIMMING_EXERCISES: ExerciseTemplate[] = [
  {
    name: "Burbujas y respiración",
    component: "WARMUP",
    minutes: 8,
    materials: "",
    space: "Piscina",
    description: "Inmersión de la cara exhalando por nariz y boca; 10 repeticiones.",
    levels: ["Adaptación"],
  },
  {
    name: "Flotación en estrella",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Flotadores",
    space: "Piscina",
    description: "Flotación ventral y dorsal con brazos y piernas extendidos; retirar el apoyo poco a poco.",
    levels: ["Adaptación"],
  },
  {
    name: "Patada con tabla",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Tablas",
    space: "Piscina",
    description: "Patada de libre desde la cadera con tabla, cara en el agua y respiración frontal.",
    levels: ["Adaptación", "Desplazamiento"],
  },
  {
    name: "Brazada con pull-buoy",
    component: "TECHNIQUE",
    minutes: 12,
    materials: "Pull-buoy",
    space: "Piscina",
    description: "Brazada de libre con respiración lateral cada 3 brazadas.",
    levels: ["Desplazamiento", "Estilos"],
  },
  {
    name: "Espalda con vaso en la frente",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Vaso plástico",
    space: "Piscina",
    description: "Nado de espalda manteniendo la cabeza quieta para corregir la posición.",
    levels: ["Estilos"],
  },
  {
    name: "Ondulación de mariposa",
    component: "TECHNIQUE",
    minutes: 10,
    materials: "Aletas",
    space: "Piscina",
    description: "Ondulación con aletas, brazos al frente, desde el pecho.",
    levels: ["Estilos", "Perfeccionamiento"],
  },
  {
    name: "Salidas desde el bloque",
    component: "SPEED",
    minutes: 15,
    materials: "Bloques",
    space: "Piscina",
    description: "Posición de salida, entrada al agua y primeras patadas subacuáticas.",
    levels: ["Perfeccionamiento", "Competencia"],
  },
  {
    name: "Vueltas de campana",
    component: "TECHNIQUE",
    minutes: 12,
    materials: "",
    space: "Piscina",
    description: "Aproximación a la pared, giro y empuje en posición hidrodinámica.",
    levels: ["Perfeccionamiento", "Competencia"],
  },
  {
    name: "Series de 50 m a ritmo",
    component: "ENDURANCE",
    minutes: 20,
    materials: "Cronómetro",
    space: "Piscina",
    description: "8 × 50 m a ritmo de prueba con 30 s de descanso.",
    levels: ["Perfeccionamiento", "Competencia"],
  },
  {
    name: "Sprints de 25 m",
    component: "SPEED",
    minutes: 15,
    materials: "Cronómetro",
    space: "Piscina",
    description: "6–8 sprints de 25 m con recuperación completa.",
    levels: ["Competencia"],
  },
  {
    name: "Nado suave de recuperación",
    component: "COOLDOWN",
    minutes: 5,
    materials: "",
    space: "Piscina",
    description: "Nado suave en el estilo preferido, respiración relajada.",
    levels: [],
  },
];

const SWIMMING_CODES = new Set(["swim", "swim-comp"]);

export function exercisesFor(code: string) {
  if (SWIMMING_CODES.has(code)) return SWIMMING_EXERCISES;
  return code === "speed" ? SPEED_EXERCISES : [];
}

/** Ejercicios comunes según el deporte de la modalidad. */
export const commonExercisesFor = (code: string) =>
  SWIMMING_CODES.has(code) ? COMMON_EXERCISES.filter((e) => !e.skatingOnly) : COMMON_EXERCISES;
